name: visprog
dependencies:
  - python=3.10
  - pip
  - pip:
    - openai==0.23.0
    - ipdb==0.13.9
    - Pillow==9.2.0
    - transformers==4.27.2
    - pytest==7.1.3
    - opencv-python==4.6.0.66
    - scipy==1.9.2
    - face-detection==0.2.2
    - augly==1.0.0
    - diffusers==0.14.0
    - accelerate==0.17.1
    - ipykernel==6.15.2
    - chardet==5.2.0
